version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: my-neo4j
    environment:
      - NEO4J_AUTH=neo4j/password  # change the password!
    ports:
      - "7474:7474"  # HTTP web UI
      - "7687:7687"  # Bolt protocol
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
